name: Build

on:
  push:
    branches: [main]
    paths:
      - 'FindMyFlipper/**'

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build for dev channel"

    strategy:
      matrix:
        sdk-channel:
          - dev
          - release
        sdk-url:
          - "https://up.momentum-fw.dev/firmware/directory.json"
          - "https://up.unleashedflip.com/directory.json"
          - "https://update.flipperzero.one/firmware/directory.json"

